### ISSUE TITLE
Switching to semver

### ISSUE THREAD

**Issue by kirillplatonov** [resque/resque-web#100]
@mcfiredrill What do you think about switching this project to semver? I think it will be useful for everybody who use this project in production.

**Comment by mcfiredrill** [comment]
@kirillplatonov I definitely want to support using semver. :100: 

Although I'm not sure what that would exactly mean for the project right now as it is not even 1.0.

Despite that, I don't think there have been any breaking changes so far.

Was there any specific change you wanted to propose right now, or do you just want to be clear on using semver going in the future?

**Comment by kirillplatonov** [comment]
@mcfiredrill Second one. I want to be clear on using semver in the future.

Talking about 1.0. I use this gem in production six month already and it doing it's job well. No critical bugs, everything works fine. Do you have any thoughts or maybe some kind of roadmap to the 1.0?

**Comment by mcfiredrill** [comment]
@kirillplatonov Sounds good to me.

Going to 1.0 sounds good too. I am not really sure what we should strive for as goals for 1.0.

The only thing I am really worried about is the plugins API. I wrote that a few years ago and it was a bit experimental, I haven't seen any other rails engine that does something similar.

Again I have to point out that personally I am no longer involved in any projects using Resque in production. I'm simply trying to help out. BTW I'm still looking for help, I can give people commit bit if needed. https://github.com/resque/resque-web/issues/92

If anyone has any thoughts or objections to going 1.0, I'd love to hear them.
