### ISSUE TITLE
API Call to get info 

### ISSUE THREAD

**Issue by ericfranckx** [resque/resque-web#102]
Hi,
is it possible to use some API or call to get info about what can see resque-web ?
Like how many queues (items in the queue) ? How many process ? on which servers ?

Regards,
Eric

**Comment by Eunoia** [comment]
You can find out this information from resque object. 

Array of queue names: `Resque.queues`
How many items in a queue: `Resque.size(name_of_queue)`
Items in a queue: `Resque.peek(name_of_queue, 0, Resque.size(name_of_queue)+1)`
Finding more about workers and their servers: `Resque.workers`

**Comment by ericfranckx** [comment]
thanks

**Comment by mcfiredrill** [comment]
There is currently no HTTP API or anything on resque-web for this. 
If that's something people are interested in I would gladly consider a PR. 📝

**Comment by Eunoia** [comment]
I'd like to work on this.

**Comment by ericfranckx** [comment]
Thanks
Eric Franckx
Global Technology Strategy Director

NGA Human Resources
The Crescent Brussels
Route de Lennik / Lenniksebaan 451
1070 Brussels
BELGIUM
Mobile: +32 477 37 69 74
Work: +32 2 558 06 70
Fax: +32 2 558 06 80
Email: eric.franckx@ngahr.com
Web: www.ngahr.com

________________________________
