### ISSUE TITLE
Form Code Visible on Page

### ISSUE THREAD

**Issue by kmentch** [resque/resque-web#104]
I deployed resque-web and everything seems to work great, however when viewing a queue page, it shows form html on the page, its the "Clear Pending Jobs" button/form. Is there something wrong somewhere in resque-web or is it on my end, and what info can I give to help diagnose.

**Comment by kmentch** [comment]
I see a fix may have already been committed for this: fbeb3dd1065d2dc4f83e849f78dab01370180962

Is this not part of the released code yet? or could something else be wrong?

**Comment by mcfiredrill** [comment]
That commit doesn't appear to be released.
Sorry I haven't released a new version in quite awhile :sweat: 
I'll try to get one out.

**Comment by mcfiredrill** [comment]
I just released 0.0.8. Can you try it out and see if its fixed?

**Comment by kmentch** [comment]
Update to 0.0.8 and this has resolved the issue. Thanks.

**Comment by mcfiredrill** [comment]
Great!
