### ISSUE TITLE
twitter-bootstrap-rails 4.0.0

### ISSUE THREAD

**Issue by tthomas7** [resque/resque-web#124]
I ran bundle update and resque_web prevented rails from rendering, instead showing, 'cannot find file twitter-bootsrap-rails/fontawesome' which makes sense given that twitter-bootstrap-rails removed font-awesome in version 4.0.0. 

I'm not sure what the permanent fix is but for me I got it working by locking twitter-bootstrap-rails to version 3.2.2 in my Gemfile. I can probably make a pull request for the gemspec file if that would be helpful.

**Comment by lumir** [comment]
Im getting the same error

**Comment by kirillplatonov** [comment]
@tthomas7 @lumir thanks for your feedback. It should be fixed in master. Would be great if you can check it within your project. I will release new version in next few days.

**Comment by kirillplatonov** [comment]
Fixed in version 0.0.10. Already available on rubygems.
