### ISSUE TITLE
Resque-Web Alternative

### ISSUE THREAD

**Issue by mlh758** [resque/resque-web#149]
You've got a really great tool here that I use in several projects. Resque-Web itself didn't quite fit my needs since I wanted something that was a little more flexible to deploy in a containerized environment. I made [this](https://github.com/mlh758/resque-web-ish) as an alternative. It doesn't have the extensibility for plugins like scheduler but it handles viewing your workers, queues, failures, and deleting failed jobs nicely.

I wanted to make sure you all were okay with it existing with that name and see if you had any feedback.

**Comment by glensc** [comment]
@mlh758 does your alternative solve this problem?:
- https://github.com/resque/resque-web/issues/154

**Comment by mlh758** [comment]
Frankly I have no idea. Are you on the latest version of this library? The line number in the stack trace doesn't line up to the line number of the function of the same name in [master](https://github.com/resque/resque/blob/master/lib/resque/data_store.rb#L224). I don't think this is necessarily an issue with this resque_web gem. It seems like you're monitoring a Node project of a similar name with this Ruby project? The implementation of Resque web is tied pretty close to how the Resque gem is written. node-resque advertises API compatibility, but I don't know how this library could guarantee that.

You could try my project and see what happens, I've never tried to point it to a cluster... But I certainly won't make any guarantees.

**Comment by glensc** [comment]
@mlh758 yes, I tried with the latest gems, the error remains.

**Comment by glensc** [comment]
@mlh758 redis cluster support needed first: https://github.com/mlh758/resque-web-ish/issues/8

**Comment by glensc** [comment]
@mlh758 also:

🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

already mentioned this to you:
- https://github.com/resque/resque-web/issues/121#issuecomment-690243609

(edit your posts, so I'll remove this comment)

**Comment by mlh758** [comment]
I edited the comment. You left that last comment in reply to something I posted a year ago, almost a year after I posted it.

**Comment by glensc** [comment]
@mlh758 I left permalinks in my comment there which you can edit your comment with.

**Comment by mlh758** [comment]
I didn't get the message because I don't pay much attention to people swooping in with a copy pasta on year old comments unrelated to the issue being discussed. I was trying to be helpful answering your questions and pointing you to relevant code from my kitchen table at 10 PM.
