### ISSUE TITLE
Rails 4 and resque-scheduler?

### ISSUE THREAD

**Issue by jschweitzer** [resque/resque-web#28]
I'm trying to use this and resque-scheduler in a Rails 4 app. Not sure where to put the "require: resque-scheduler/server" bit in this deployment setup. (https://github.com/resque/resque-scheduler#how-do-i-get-the-schedule-tabs-to-show-up) since I don't have a config file

**Comment by kirillplatonov** [comment]
https://github.com/mattgibson/resque-scheduler-web

**Comment by mcfiredrill** [comment]
@kirillplatonov Nice, I had no idea that existed. Would be cool to add it to the README perhaps.

**Comment by kirillplatonov** [comment]
Added section about resque web plugins to readme https://github.com/resque/resque-web#existing-plugins
