### ISSUE TITLE
ApplicationHelper not loading

### ISSUE THREAD

**Issue by gpeal** [resque/resque-web#29]
I have ResqueWeb mounted in a rails 4.0.0 app. Resque web works for the first few times after the server starts up but quickly after, any class to ApplicationHelper methods throw errors such as:
`<%= pagination :start => failure_start_at, :total => failure_size unless params[:class] %>`

**Comment by mcfiredrill** [comment]
I believe this is fixed in https://github.com/resque/resque-web/pull/79
and I have released an updated version of the Gem with this fix. Please feel free to reopen if you are still getting this error.

**Comment by take** [comment]
did anyone confirm this error is fixed in resque-web 0.0.7? :eyes: (release of #79
