### ISSUE TITLE
redis authentication

### ISSUE THREAD

**Issue by benholtz** [resque/resque-web#55]
Hello, I'm trying to get this newer version of the application working, however I'm having a tough time finding how to add a password for redis authentication.  previously I had added the following(below) to the /config/environment.rb to override values.  Can you help point me in the right direction?
Resque.redis = Redis.new(:host => "redis.server.local", :port => 6379, :password => "foo")

**Comment by gnazarkin** [comment]
Same issue. @benholtz you just remove the password to get it to work?

**Comment by kirillplatonov** [comment]
@gnazarkin I merged ability to set resque password in env variable. Try it https://github.com/resque/resque-web/commit/ccb51fb492efdfc485f2b7bdd82238ccd3a82c18

**Comment by gnazarkin** [comment]
@kirillplatonov Thanks, got it to work
