### ISSUE TITLE
Navigations links are missing

### ISSUE THREAD

**Issue by calvinl** [resque/resque-web#96]
Here's my panel:

<img width="1191" alt="screen shot 2015-10-29 at 2 21 39 pm" src="https://cloud.githubusercontent.com/assets/490687/10828004/704cb706-7e48-11e5-923c-a2919bd510db.png">
 
The nav links are actually there if I inspect the header, but they don't show. Looks like a CSS issue. 

Is anyone still working on this project?

**Comment by aaani** [comment]
I have the same issue on heroku. Although locally if I run bundle exec resque-web I see the navigation links.

**Comment by mcfiredrill** [comment]
I think this might be fixed in the latest version of the Gem `0.0.7`. Are you using the latest version @aaani  ?

**Comment by aaani** [comment]
@mcfiredrill Thanks. It's fixed in 0.0.7 indeed.

**Comment by aaani** [comment]
Sorry, I forgot to reply. @mcfiredrill Using the latest version fixed the issue for me.
